export default {
  any: {
    dene: "Deneme yazısına {{var}} ekledim",
    home: "Ana sayfa",
    dashboard: "Gösterge Paneli",
    options: "Ayarlar",
    logout: "Çıkış",
    users: "Kullanıcılar",
    layouts: "Düzenler",
    fullName: "İsim Soyisim",
    name: "İsim",
    email: "Eposta",
    password: "Şifre",
    retypePassword: "Şifre tekrar",
    trash: "Silinenler",
    permissions: "İzinler",
    language: "Dil",

    description: "Açıklama",
    firstName: "İsim",
    lastName: "Soyisim",
    role: "Rol",
    roles: "Roller",
    username: "Kullanıcı adı",
    nickname: "Takma ad",
    image: "Resim",
    createdAt: "Oluşturulma tarihi",
    updatedAt: "Güncellenme tarihi",
    deletedAt: "Silinme tarihi",
    trash: "Çöp Kutusu",
    moveToTrash: "Çöp Kutusuna Taşı",
    delete: "Sil",
    restore: "Geri Al",
    deletePermanently: "Kalıcı Olarak Sil",
    status: "Durum",
    title: "Başlık",
    content: "İçerik",
    search: "Ara",
    trash: "Silinenler",
    addNew: "Yeni Ekle",
    save: "Kaydet",
    edit: "Düzenle",
    body: "Gövde",
    noElementFound: "Öğe Bulunamadı!",
    shownRecord: "Sayfada gösterilen kayıt:",

    which: "Hangi Alan",
    status: "Durum",
    name: "İsim",
    top: "Üst",
    bottom: "Alt",
    active: "Aktif",
    passive: "Pasif",
    header: "Header",
    footer: "Footer",
    leftSidebar: "Sol Yan Alan",
    rightSidebar: "Sağ Yan Alan",
    selectAll: "Hepsini Seç",
    customize: "Özelleştir",
    darkMode: "Karanlık Mod",
    noBorder: "Çerçeve Yok",
    fixed: "Sabit",
    collapsed: "Daralt",
    navFlat: "Düz Menu",
    navLegacy: "Miras Menu",
    navCompact: "Sıkı Menu",
    navChildIndent: "Menu Alt Girinti",
    navChildHideOnCollapse: "Menü Daraltıldığında Alt Elemanı Gizle",
    disableHoverFocusAutoExpand: "Hover/Odak Otomatik Genişletmeyi Devre Dışı Bırak",
    headerOptions: "Başlık Seçenekleri",
    sidebarOptions: "Kenarlık Seçenekleri",
    footerOptions: "Altbilgi Seçenekleri",
    smallTextOption: "Küçük Metin Seçenekleri",
    navbarVariants: "Menü Varyantları",
    sidebarVariants: "Kenarlık Varyantları",
    brandLogoVariants: "Marka Logo Varyantları",
    noneSelected: "Hiçbiri",
    primary: "Birincil",
    secondary: "İkincil",
    info: "Bilgi",
    warning: "Uyarı",
    success: "Başarı",
    danger: "Tehlike",
    indigo: "Çivit",
    purple: "Mor",
    pink: "Pembe",
    navy: "Lacivert ",
    lightblue: "Açık Mavi",
    cyan: "Camgöbeği",
    dark: "Karanlık",
    grayDark: "Koyu Gri",
    gray: "Gri",
    light: "Açık",
    white: "Beyaz",
    orange: "Turuncu",
    fuchsia: "Fuşya",
    maroon: "Bordo",
    lime: "Limon Yeşili",
    teal: "Deniz Mavisi",
    olive: "Zeytin Yeşili",
  },
  permission: {
    postSearch: "Yazı Arama",
    postCreate: "Yazı Oluşturma",
    postRead: "Yazı Okuma",
    postUpdate: "Yazı Düzenleme",
    postDelete: "Yazı Silme",
    userSearch: "Kullanıcı Arama",
    userCreate: "Kullanıcı Oluşturma",
    userRead: "Kullanıcı Okuma",
    userUpdate: "Kullanıcı Düzenleme",
    userDelete: "Kullanıcı Silme",
    roleSearch: "Rol Arama",
    roleCreate: "Rol Oluşturma",
    roleRead: "Rol Okuma",
    roleUpdate: "Rol Düzenleme",
    roleDelete: "Rol Sil",
    pageSearch: "Sayfa Arama",
    pageCreate: "Sayfa Oluşturma",
    pageRead: "Sayfa Okuma",
    pageUpdate: "Sayfa Düzenleme",
    pageDelete: "Sayfa Silme",
  },
  footer: {
    text: "Ne isterseniz",
    rights: "Tüm Hakları Saklıdır.",
    copyright: "Telif Hakkı"
  },
  login: {
    message: "Oturumunuzu başlatmak için giriş yapın",
    rememberMe: "Beni Hatırla",
    signIn: "Giriş",
    forgetPassword: "Şifremi unuttum",
    registerNew: "Yeni üyelik kaydı",
  },
  register: {
    message: "Yeni üyelik kaydı",
    register: "kaydol",
    alreadyMember: "Zaten üyeyim",
  },
  password: {
    message: "Şifrenizi mi unuttunuz? Burdan kolayca şifre alabilirsiniz.",
    requestNew: "Yeni şifre isteği",
    login: "Giriş",
  },
  notify: {
    languagePreferenceSaved: "Dil Tercihi Kaydedildi",
    deletedSuccessfully: "{{title}} Başarılı Şekilde Silindi",
    createdSuccessfully: "{{title}} Başarılı Şekilde Oluşturuldu",
    updatedSuccessfully: "{{title}} Başarılı Şekilde Güncellendi",
    restoredSuccessfully: "Başarılı Şekilde Geri Alındı",
  },
  error: {
    dontHavePermission: "Bu işlem için izniniz yok!",
    emailIsWrong: "Email Hatalı!",
    usernameIsWrong: "Kullanıcı Adı Hatalı!",
    passwordIsIncorrect: "Şifre Hatalı!",
    accessTokenNotSent: "Access Token Gönderilmedi!",
    accessTokenNotFound: "Access Token Bulunamadı!",
    accessTokenExpired: "Access Token Süresi Doldu!",
    userNotFound: "Kullanıcı Bulunamadı!",
    nameMustNotBeEmpty: "İsim Boş Olmamalı!",
    firstNameMustNotBeEmpty: "İsim Boş Olmamalı!",
    lastNameMustNotBeEmpty: "Soyisim Boş Olmamalı!",
    roleNotAllowed: "Role İzin Verilmedi!",
    emailNotValid: "Email Geçerli Formatta Değil!",
    usernameMustBeSent: "Kullanıcı Adı Göndeilmedi!",
    passwordNotValid: "Şifre Uygun Formatta Değil!",
    passwordsNotMatch: "Şifreler Uyuşmuyor!",
    linkNotFound: "Link Bulunamadı!",
    ownerNotAllowed: "Sahiplik İzin Verilmiyor!",
    pathMustNotBeEmpty: "Yol Boş Olmamalı!",
    languageIdMustBePositiveNumber: "Dil Kimliği Pozitif Sayı Olmalıdır!",
    roleCanNotDeletedSomeUsersHasIt: "Rol Silinemez. Bazı Kullanıcılar Bu Role Sahiptir!",
    roleNotFound: "Rol Bulunamadı!",
    roleMustBeSent: "Rol Gönderilmeli!",
    postNotFound: "Gönderi Bulunamadı!",
    slugIdMustBePositiveNumber: "Slug Kimliği Pozitif Sayı Olmalıdır!",
    userIdMustBePositiveNumber: "Kullanıcı Kimliği Pozitif Sayı Olmalıdır!",
    statusNotAllowed: "Durum Bilgisi İzin Verilmiyor!",
    getNotAllowed: "Get İzin Verilmiyor!",
    optionNotFound: "Seçenek Bulunamadı!",
    optionsNotFound: "Seçenekler Bulunamadı!",
    typeMustNotBeEmpty: "Tür Boş Olmamalı!",
    typeIdMustBeInteger: "Tür Kimliği Tam Sayı Olmalıdır!",
    keyMustNotBeEmpty: "Anahtar Boş Olmamalı!",
    categoryNotFound: "Kategori Bulunamadı!",
    fileIdMustBePositiveNumber: "Dosya Kimliği Pozitif Sayı Olmalıdır!",
    parentIdMustBePositiveNumber: "Ebeveyn Kategory Kimliği Pozitif Sayı Olmalıdır!",
    autoLinkNotFound: "Otomatik Bağlantı Bulunamadı!",
    wordMustNotBeEmpty: "Kelime Boş Olmamalı!",
    uriMustNotBeEmpty: "Uri Boş Olmamalı!",
    authUserCanNotDeleteOwnProfile: "Oturum Sahibi Kendi Profilini Silemez",
    titleMustNotBeEmpty: "Başlık Boş Olmamalı!",
    layoutNotAllowed: "Yerleşim Seçenekleri Arasında Yok!",
    statusNotAllowed: "Durum Seçenekleri Arasında Yok!",
    languageIdMustBeInteger: "Dil Id'si Numara Olmalı!",
  }
}