export default {
  any: {
    dene: "I added {{var}} to test line",
    home: "Home",
    dashboard: "Dashboard",
    options: "Options",
    users: "Users",
    logout: "Logout",
    layouts: "Layouts",
    fullName: "Full name",
    name: "Name",
    email: "Email",
    password: "Password",
    retypePassword: "Retype password",
    trash: "Trash",
    permissions: "Permissions",
    language: "Language",

    description: "Description",
    firstName: "First Name",
    lastName: "Last Name",
    role: "Role",
    roles: "Roles",
    username: "Username",
    nickname: "Nickname",
    image: "Image",
    createdAt: "Created At",
    updatedAt: "Updated At",
    deletedAt: "Deleted At",
    trash: "Trash",
    moveToTrash: "Move To Trash",
    delete: "Delete",
    restore: "Restore",
    deletePermanently: "Delete Permanently",
    status: "Status",
    title: "Title",
    content: "Content",
    search: "Search",
    trash: "Trash",
    addNew: "Add New",
    save: "Save",
    edit: "Edit",
    body: "Body",
    noElementFound: "No Element Found!",
    shownRecord: "The record shown on the page:",
    
    which: "Which",
    status: "Status",
    name: "Name",
    top: "Top",
    bottom: "Bottom",
    active: "Active",
    passive: "Passive",
    header: "Header",
    footer: "Footer",
    leftSidebar: "Left Sidebar",
    rightSidebar: "Right Sidebar",
    selectAll: "Select All",
    customize: "Customize",
    darkMode: "Dark Mode",
    noBorder: "No Border",
    fixed: "Fixed",
    collapsed: "Collapsed",
    navFlat: "Nav Flat",
    navLegacy: "Nav Legacy",
    navCompact: "Nav Compact",
    navChildIndent: "Nav Child Indent",
    navChildHideOnCollapse: "Nav Child Hide On Collapse",
    disableHoverFocusAutoExpand: "Disable Hover/Focus Auto-Expand",
    headerOptions: "Header Options",
    sidebarOptions: "Sidebar Options",
    footerOptions: "Footer Options",
    smallTextOption: "Small Text Options",
    navbarVariants: "Navbar Variants",
    sidebarVariants: "Sidebar Variants",
    brandLogoVariants: "Brand Logo Variants",
    noneSelected: "None Selected",
    primary: "Primary",
    secondary: "Secondary",
    info: "Info",
    warning: "Warning",
    success: "Success",
    danger: "Danger",
    indigo: "Indigo",
    purple: "Purple",
    pink: "Pink",
    navy: "Navy",
    lightblue: "Lightblue",
    cyan: "Cyan",
    dark: "Dark",
    grayDark: "Gray dark",
    gray: "Gray",
    light: "Light",
    white: "White",
    orange: "Orange",
    fuchsia: "Fuchsia",
    maroon: "Maroon",
    lime: "Lime",
    teal: "Teal",
    olive: "Olive",
  },
  permission: {
    postSearch: "Search Post",
    postCreate: "Create Post",
    postRead: "Read Post",
    postUpdate: "Update Post",
    postDelete: "Delete Post",
    userSearch: "Search User",
    userCreate: "Create User",
    userRead: "Read User",
    userUpdate: "Update User",
    userDelete: "Delete User",
    roleSearch: "Search Role",
    roleCreate: "Create Role",
    roleRead: "Read Role",
    roleUpdate: "Update Role",
    roleDelete: "Delete Role",
    pageSearch: "Search Page",
    pageCreate: "Create Page",
    pageRead: "Read Page",
    pageUpdate: "Update Page",
    pageDelete: "Delete Page",
  },
  footer: {
    text: "Anything you want",
    rights: "All rights reserved.",
    copyright: "Copyright"
  },
  login: {
    message: "Sign in to start your session",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    forgetPassword: "I forgot my password",
    registerNew: "Register a new membership",
  },
  register: {
    message: "Register a new membership",
    register: "Register",
    alreadyMember: "I already have a membership",
  },
  password: {
    message: "You forgot your password? Here you can easily retrieve a new password.",
    requestNew: "Request new password",
    login: "Login",
  },
  notify: {
    languagePreferenceSaved: "Language preference Saved",
    deletedSuccessfully: "{{title}} Deleted Successfully",
    createdSuccessfully: "{{title}} Created Successfully",
    updatedSuccessfully: "{{title}} Updated Successfully",
    restoredSuccessfully: "Restored Successfully",
  },
  error: {
    dontHavePermission: "You do not have permission for this operation!",
    emailIsWrong: "Email Is Wrong!",
    usernameIsWrong: "Username Is Wrong!",
    passwordIsIncorrect: "Password Is Wrong!",
    accessTokenNotSent: "Access Token Not Sent!",
    accessTokenNotFound: "Access Token Not Found!",
    accessTokenExpired: "Access Token Expired!",
    userNotFound: "User Not Found!",
    nameMustNotBeEmpty: "Name Must Not Be Empty!",
    firstNameMustNotBeEmpty: "First Name Must Not Be Empty!",
    lastNameMustNotBeEmpty: "Last Name Must Not Be Empty!",
    roleNotAllowed: "Role Not Allowed!",
    emailNotValid: "Email Not Valid!",
    usernameMustBeSent: "Username Must Be Sent!",
    passwordNotValid: "Password Not Valid!",
    passwordsNotMatch: "Passwords Not Match!",
    linkNotFound: "Link Not Found!",
    ownerNotAllowed: "Owner Not Allowed!",
    pathMustNotBeEmpty: "Path Must Not Be Empty!",
    languageIdMustBePositiveNumber: "Language Id Must Be Positive Number!",
    roleCanNotDeletedSomeUsersHasIt: "Role Cannot Be Deleted. Some Users Has This Role!",
    roleNotFound: "Role Not Found!",
    roleMustBeSent: "Role Must Be Sent!",
    postNotFound: "Post Not Found!",
    slugIdMustBePositiveNumber: "Slug Id Must Be Positive Number!",
    userIdMustBePositiveNumber: "User Id Must Be Positive Number!",
    statusNotAllowed: "Status Not Allowed!",
    getNotAllowed: "Get Not Allowed!",
    optionNotFound: "Option Not Found!",
    optionsNotFound: "Options Not Found!",
    typeMustNotBeEmpty: "Type Must Not Be Empty!",
    typeIdMustBeInteger: "Type Id Must Be Integer!",
    keyMustNotBeEmpty: "Key Must Not Be Empty!",
    categoryNotFound: "Category Not Found!",
    fileIdMustBePositiveNumber: "File Id Must Be Positive Number!",
    parentIdMustBePositiveNumber: "Parent Category Id Must Be Positive Number!",
    autoLinkNotFound: "Auto Link Not Found!",
    wordMustNotBeEmpty: "Word Must Not Be Empty!",
    uriMustNotBeEmpty: "Uri Must Not Be Empty!",
    authUserCanNotDeleteOwnProfile: "Auth User Can Not Delete Own Profile!",
    titleMustNotBeEmpty: "Title Must Not Be Empty!",
    layoutNotAllowed: "Yerleşim Not Allowed!",
    statusNotAllowed: "Status Not Allowed!",
    languageIdMustBeInteger: "Languade Id Must Be Integer!",
  }
}